# Generated by Django 3.2 on 2021-11-11 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usermanager', '0004_permanentuserdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permanentuserdata',
            name='index',
        ),
        migrations.DeleteModel(
            name='Temporarystorage',
        ),
        migrations.DeleteModel(
            name='PermanentUserData',
        ),
    ]
