# Generated by Django 3.2 on 2021-09-26 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formmcqquestions',
            name='code',
            field=models.CharField(max_length=100),
        ),
    ]
