# Generated by Django 3.2 on 2021-11-25 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_rename_formmcqtypequestions_formmcqtyperesponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='formpublicdata',
            name='show_response',
            field=models.BooleanField(default=False),
        ),
    ]
