# Generated by Django 3.2 on 2021-11-11 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_formmcqquestions_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='formFillTypeQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('question', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='formFillTypeResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
