# Generated by Django 3.2 on 2021-11-25 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_formpublicdata_show_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='formpublicdata',
            name='accept_response',
            field=models.BooleanField(default=True),
        ),
    ]
