# Generated by Django 3.2 on 2021-11-26 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_formpublicdata_accept_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='formpublicdata',
            name='open_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formpublicdata',
            name='open_till',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
