# Generated by Django 3.2 on 2021-11-18 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizform', '0002_auto_20211118_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizmanager',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
