# Generated by Django 3.2 on 2021-11-18 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizform', '0003_quizmanager_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizmcqanswers',
            name='answers',
            field=models.TextField(blank=True, null=True),
        ),
    ]
