# Generated by Django 3.2 on 2021-11-19 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizform', '0006_auto_20211119_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filltypeuserresponses',
            name='final_marks',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='mcqtypeuserresponses',
            name='final_marks',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='quizfilltypequestions',
            name='marks',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='quizmcqquestions',
            name='marks',
            field=models.FloatField(default=0),
        ),
    ]
