# Generated by Django 3.2 on 2021-11-22 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizform', '0007_auto_20211119_1557'),
    ]

    operations = [
        migrations.CreateModel(
            name='option_survey_mcq_response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option1', models.BooleanField(default=False)),
                ('option2', models.BooleanField(default=False)),
                ('option3', models.BooleanField(default=False)),
                ('option4', models.BooleanField(default=False)),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizform.mcqtypeuserresponses')),
            ],
        ),
    ]
