# Generated by Django 3.2 on 2021-11-22 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizform', '0008_option_survey_mcq_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option_survey_mcq_response',
            name='option1',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='option_survey_mcq_response',
            name='option2',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='option_survey_mcq_response',
            name='option3',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='option_survey_mcq_response',
            name='option4',
            field=models.FloatField(default=0),
        ),
    ]
