# Generated by Django 3.2 on 2021-11-25 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizform', '0010_quizmanager_show_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizmanager',
            name='accept_response',
            field=models.BooleanField(default=True),
        ),
    ]
