# Generated by Django 3.2 on 2021-11-28 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizform', '0011_quizmanager_accept_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizmanager',
            name='open_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quizmanager',
            name='open_till',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
